
spring :
  datasource:
    url: jdbc:sqlserver://192.168.1.248:1433;databaseName=RestfulAPI
    username: sa
    password: tap@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: sql_server
#    database-platform: org.hibernate.dialect.SQLServerDialect
server:
  port: 8083
